version: "2"
services:
  lb:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.warehouse.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - worker-web
  web:
    build: .
    environment:
      NODE_ENV: local
      MONGOLAB_URI: mongodb://db:27017/warehouse-local
      SCHEME: http
    env_file: 
      - .env
    command: node server/server.js
    volumes:
      - .:/apps/warehouse
  worker-web:
    build: .
    environment:
      NODE_ENV: local
      MONGOLAB_URI: mongodb://db:27017/warehouse-local
    env_file: 
      - .env
    command: nodemon -L --debug=5858
    volumes:
      - .:/apps/warehouse
  worker:
    build:
      context: ./warehouse-workers
    working_dir: /apps/workers
    command: node sqsWorker.js
    volumes:
      - ./warehouse-workers:/apps/workers
    restart: always
    env_file: worker.env
    depends_on:
      - memcache
  db:
    image: mongo:3.2
    ports:
      - "27018:27017"
  memcache:
    image: memcached:latest
